name: prueba
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Dependencias agregadas para SQLite
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.1

  # State Management
  provider: ^6.1.1

  # UI
  google_fonts: ^6.1.0
  fl_chart: ^1.1.0  # Versión más reciente

  # Utilities
  intl: ^0.20.2  # Versión más reciente

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter de buenas prácticas
  flutter_lints: ^6.0.0  # Versión más reciente

  # Herramienta para cambiar el ícono de la app
  flutter_launcher_icons: ^0.14.4  # Versión más reciente

  flutter_native_splash: ^2.4.0

flutter:
  # Fuente de íconos de Material Design
  uses-material-design: true

  # Registro de recursos (incluye tu ícono)
  assets:
    - assets/icon/pines.png
    - assets/icon/pinesB.png
    - assets/images/
    - assets/icons/

# Configuración de iconos de la app
flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/pines.png"

# Configuración de splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/pinesB.png
  
  android_gravity: center
  android_12:
    image: assets/icon/pinesB.png
    color: "#FFFFFF"
  
  ios_content_mode: scaleAspectFill
  web_image_mode: center
  fullscreen: true