name: prueba
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Dependencias agregadas para SQLite
  sqflite: ^2.3.0
  path: ^1.9.0
  rename: ^3.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter de buenas prácticas
  flutter_lints: ^5.0.0

  # Herramienta para cambiar el ícono de la app
  flutter_launcher_icons: ^0.13.1

  flutter_native_splash: ^2.4.0

flutter:

  # Fuente de íconos de Material Design
  uses-material-design: true

  # Registro de recursos (incluye tu ícono)
  assets:
    - assets/icon/pines.png

# 👇 Esta parte va FUERA del bloque "flutter:"
flutter_icons:
  android: true
  ios: false  # Cámbialo a true si también quieres cambiarlo en iOS
  image_path: "assets/icon/pines.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/pinesB.png
  
  android_gravity: center
  android_12:
    image: assets/icon/pinesB.png
    color: "#FFFFFF"
  
  # Probar con fill en lugar de center
  ios_content_mode: scaleAspectFill
  
  web_image_mode: center
  fullscreen: true

